### PR TITLE
fix(js-plugin-electron): dependencies unintentionally marked as external

### PR DESCRIPTION
**Pull request by JellyBrick**
**Description:** fixed an issue where dependencies were unintentionally marked as `external`
- caused by https://github.com/farm-fe/farm/blob/7481a2321049aaf6e767a7c246c5e0f414dd745f/js-plugins/electron/src/index.ts#L117
  - This code was causing dependencies, such as `electron-*` that matched the `electron` (regex), to be marked as `external`.

**BREAKING CHANGE:** x

**Related issue (if exists):**

### CODE REVIEW

**Review by ErKeLost — APPROVED** [review]

**Comment by wre232114** [comment]
Thanks!

**Review by wre232114 — APPROVED** [review]

**Review by caoxiemeihao — APPROVED** [review]
LGTM

**Review by shulandmimi — CHANGES_REQUESTED** [review]
Execute `npx changeset` in the project root directory and select @farmfe/js-plugin-electron to generate a changeset file

**Review by fu050409 — APPROVED** [review]

**Review by shulandmimi — APPROVED** [review]

**Comment by ErKeLost** [comment]
Looks like electron example ci failed

**Pull request merged**
