### PR TITLE
build: linux arm64 support

### PR DESCRIPTION
**Pull request by rhyzx**
## Description:
Add Linux ARM64 support.
All builds have passed. See [this link](https://github.com/rhyzx/farm/actions/runs/6904194415).

## BREAKING CHANGE:
N/A

### CODE REVIEW

**Comment by wre232114** [comment]
thanks

**Comment by wre232114** [comment]
CI failed

**Comment by rhyzx** [comment]
> CI failed

It's from the legacy code coverage test, caused by a crate using an experimental feature `std::io::IsTerminal` which has become stable since version 1.70. I've resolved this by upgrading Rust.

----
Then encountered some lint issues 😅, working on them.

**Comment by wre232114** [comment]
examples tests failed, I think it's caused by the  wrong artifacts download location

**Pull request merged**
