### PR TITLE
refactor(v2): use faster hasher to optimize

### PR DESCRIPTION
**Pull request by fu050409**
**Description:**

**BREAKING CHANGE:**

**Related issue (if exists):**

### CODE REVIEW

**Comment by wre232114** [comment]
You can rename `FxHashMap` to `HashMap` and reexport them at the place. So all usage will not be changed, also it's easy to update the hash implementation in the future

**Comment by wre232114** [comment]
yeah, it's fine

**Review by wre232114 — COMMENTED** [review]
can we add a new() method for the faster hashmap, then we don't need to replace all the new() to default()

**Comment by fu050409** [comment]
> can we add a new() method for the faster hashmap, then we don't need to replace all the new() to default()

I'm afraid not. The method `new()` is provided by the Rust standard library. And in soruce code, it is:

```
#[inline]
#[must_use]
#[stable(feature = "rust1", since = "1.0.0")]
pub fn new() -> HashMap<K, V, RandomState> {
    Default::default()
}
```

As we can see, this method is for `HashMap` with `RandomState` so it's not implemented for `FxHashBuilder`.

Otherwise, we cannout define inherent `impl` for foreign type.

**Review by wre232114 — APPROVED** [review]

**Pull request merged**
