### PR TITLE
docs(README): add graphs contributors

### PR DESCRIPTION
**Pull request by liangchaofei**
**Description:**

add graphs contributors

**BREAKING CHANGE:**

**Related issue (if exists):**

### CODE REVIEW

**Review by ErKeLost — APPROVED** [review]

**Comment by ErKeLost** [comment]
thanks The spelling of the word needs to be corrected

**Comment by liangchaofei** [comment]
> thanks The spelling of the word needs to be corrected

which word?

**Comment by ErKeLost** [comment]
(ci failed)[https://github.com/farm-fe/farm/actions/runs/8136327124/job/22232416563?pr=999] Line 900

**Comment by liangchaofei** [comment]
> [ci failed](https://github.com/farm-fe/farm/actions/runs/8136327124/job/22232416563?pr=999) Line 900

I see this line, but I do not know which word. Can you help me?

image

**Comment by ErKeLost** [comment]
> > [ci failed](https://github.com/farm-fe/farm/actions/runs/8136327124/job/22232416563?pr=999) Line 900
> 
> I see this line, but I do not know which word. Can you help me?
> 
> image

`srcset`

**Pull request merged**
