### PR TITLE
chore: support postcss

### LINKED ISSUE #126: [Feature]: support postcss

### PR DESCRIPTION
**Pull request by wre232114**
**Description:**

**BREAKING CHANGE:**

**Related issue (if exists):**
close #126

### CODE REVIEW

**Comment by molvqingtai** [comment]
**Support tailwindcss**

I have tried, but I need to trigger `rebuild` to make [tailwindcss jit](https://v2.tailwindcss.com/docs/just-in-time-mode#styles-don-t-update-when-saving-content-files) effective.

Https://github.com/postcss/postcss/blob/main/docs/guidelines/runner.md#3-dependencies

If it can be like `esbuild`, it can return `watchFiles` in `LoadHookResult`, it should be easy to implement.

**Comment by wre232114** [comment]
Thanks! Farm support add more files during build too. I'll add this feature to plugin-postcss

**Comment by wre232114** [comment]
looks like tailwindcss 3 does not needs postcss dependencies for JIT any more. https://tailwindcss.com/docs/upgrade-guide#migrating-to-the-jit-engine

**Comment by skywalker512** [comment]
https://github.com/skywalker512/farm-vue-sfc-reproduce

**Pull request merged**
