### PR TITLE
refactor(v2): rewrite preview-server

### PR DESCRIPTION
**Pull request by fu050409**
Resolved: #1842

### CODE REVIEW

**Comment by ErKeLost** [comment]
preview server After I integrate server middleware, let me take a look at this pr

**Comment by fu050409** [comment]
Please wait while I am working on refactoring the configs, I should support middlewares inherit from dev server so this may take a day to resolve it ：）

**Comment by fu050409** [comment]
I apologise for consuming more time than expected due to some personal reasons and some exams, but I'm glad the preview server is working properly and ready for review now :D

**Comment by fu050409** [comment]
ok, i will triger it tonight

**Comment by ErKeLost** [comment]
Or we can combine this pr first, and then the problem of hooks can be put on the next pr， so we can resolve conflicts first.

**Review by ErKeLost — APPROVED** [review]

**Pull request merged**
