### PR TITLE
refactor(watcher): optimize file watch and support watch `node_modules`

### LINKED ISSUE #949: Optimize file watch when adding modules in HMR
### What problem does this feature solve?

Currently If a HMR adds a lot of modules, all these modules will be added to the watch list.

We should only watch the common root of these modules

### What does the proposed API look like?

1. record watched paths
2. find common root of the watched paths instead of watching all added modules paths

### LINKED ISSUE #1212: Support watch files under node_modules
### What problem does this feature solve?

Sometimes we need to modify files under node modules and enabled hmr for it

### What does the proposed API look like?

support configuring watch node modules:
image

### PR DESCRIPTION
**Pull request by fu050409**
Resolved #1212, Resolved #949

### CODE REVIEW

**Comment by ErKeLost** [comment]
The watcher may have to wait until the server and hmr functions are completed before it can be started.

The watcher should be configured according to vite. Maybe we can reconstruct the watch node mode first ？

**Comment by fu050409** [comment]
> The watcher may have to wait until the server and hmr functions are completed before it can be started.
> 
> The watcher should be configured according to vite. Maybe we can reconstruct the watch node mode first ？

Yes, I am going to do this. And I am now trying to resolve #949 first and then I will refactor the watcher login to make it works like vite.

**Comment by fu050409** [comment]
In fact, as you can see in #1598, we need to do much more than that in terms of refactoring the watcher. There are still some unimplemented features in the watcher.

**Comment by fu050409** [comment]
Changes all resolved in #1735, close this pull request.

**Pull request closed without merging**
